#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.9
# from Racc grammer file "".
#

require 'racc/parser.rb'

#
# generated by racc
#
require "lib/AST/AbstractMethodException"
require "lib/AST/AllExpression"
require "lib/AST/AndExpression"
require "lib/AST/AnyExpression"
require "lib/AST/AsExpression"
require "lib/AST/BagExpression"
require "lib/AST/BinaryExpression"
require "lib/AST/BooleanTerminal"
require "lib/AST/CommaExpression"
require "lib/AST/DifferentExpression"
require "lib/AST/DivideExpression"
require "lib/AST/DotExpression"
require "lib/AST/EqualExpression"
require "lib/AST/Expression"
require "lib/AST/FloatTerminal"
require "lib/AST/GreatherEqualExpression"
require "lib/AST/GreatherExpression"
require "lib/AST/GroupAsExpression"
require "lib/AST/IncorrectArgumentException"
require "lib/AST/IntegerTerminal"
require "lib/AST/InExpression"
require "lib/AST/IntersectExpression"
require "lib/AST/LessEqualExpression"
require "lib/AST/LessExpression"
require "lib/AST/MinusExpression"
require "lib/AST/ModuloExpression"
require "lib/AST/MultiplyExpression"
require "lib/AST/NameExpression"
require "lib/AST/OrExpression"
require "lib/AST/PlusExpression"
require "lib/AST/StringTerminal"
require "lib/AST/StructExpression"
require "lib/AST/TerminalExpression"
require "lib/AST/UnaryExpression"
require "lib/AST/UnionExpression"
require "lib/AST/UniqueExpression"
require "lib/AST/Utils"
require "lib/AST/WhereExpression"
require "lib/AST/SetMinusExpression"

require 'lib/Parser/SBQL.rex'

include AST
class SBQLParser < Racc::Parser
##### State transition tables begin ###

racc_action_table = [
    34,    35,    39,    13,    43,    45,    47,    50,    52,     2,
     5,    32,     7,    10,    12,    14,    16,    48,    20,    53,
    30,    31,    33,    36,    37,    40,    42,    44,    46,    49,
    51,     3,    28,     6,     8,    38,    41,    15,    17,    18,
    19,    21,     1,     4,    34,    35,    39,    13,    43,    45,
    47,    50,    52,     2,     5,    32,     7,    10,    12,    14,
    16,    48,    20,    53,    30,    31,    33,    36,    37,    40,
    42,    44,    46,    49,    51,     3,    34,     6,     8,    38,
    41,    15,    17,    18,    19,    21,     1,     4,    13,    34,
    35,    39,    62,    65,     2,     5,    72,     7,    10,    12,
    14,    16,    13,    20,    34,    35,    39,   nil,     2,     5,
   nil,     7,    10,    12,    14,    16,     3,    20,     6,     8,
   nil,   nil,    15,    17,    18,    19,    21,     1,     4,   nil,
     3,   nil,     6,     8,   nil,   nil,    15,    17,    18,    19,
    21,     1,     4,    13,    34,    35,    39,   nil,   nil,     2,
     5,   nil,     7,    10,    12,    14,    16,    13,    20,    34,
    35,    39,   nil,     2,     5,   nil,     7,    10,    12,    14,
    16,     3,    20,     6,     8,   nil,   nil,    15,    17,    18,
    19,    21,     1,     4,   nil,     3,   nil,     6,     8,   nil,
   nil,    15,    17,    18,    19,    21,     1,     4,    13,    34,
    35,    39,   nil,   nil,     2,     5,   nil,     7,    10,    12,
    14,    16,    13,    20,    34,    35,    39,   nil,     2,     5,
   nil,     7,    10,    12,    14,    16,     3,    20,     6,     8,
   nil,   nil,    15,    17,    18,    19,    21,     1,     4,   nil,
     3,   nil,     6,     8,   nil,   nil,    15,    17,    18,    19,
    21,     1,     4,    13,    34,    35,    39,   nil,   nil,     2,
     5,   nil,     7,    10,    12,    14,    16,    13,    20,    34,
    35,    39,   nil,     2,     5,   nil,     7,    10,    12,    14,
    16,     3,    20,     6,     8,   nil,   nil,    15,    17,    18,
    19,    21,     1,     4,   nil,     3,   nil,     6,     8,   nil,
   nil,    15,    17,    18,    19,    21,     1,     4,    13,    34,
    35,    39,   nil,   nil,     2,     5,   nil,     7,    10,    12,
    14,    16,    13,    20,    34,    35,    39,   nil,     2,     5,
   nil,     7,    10,    12,    14,    16,     3,    20,     6,     8,
   nil,   nil,    15,    17,    18,    19,    21,     1,     4,   nil,
     3,   nil,     6,     8,   nil,   nil,    15,    17,    18,    19,
    21,     1,     4,    13,    34,    35,    39,   nil,   nil,     2,
     5,   nil,     7,    10,    12,    14,    16,    13,    20,    34,
    35,    39,   nil,     2,     5,   nil,     7,    10,    12,    14,
    16,     3,    20,     6,     8,   nil,   nil,    15,    17,    18,
    19,    21,     1,     4,   nil,     3,   nil,     6,     8,   nil,
   nil,    15,    17,    18,    19,    21,     1,     4,    13,    34,
    35,    39,   nil,   nil,     2,     5,   nil,     7,    10,    12,
    14,    16,    13,    20,    34,    35,    39,   nil,     2,     5,
   nil,     7,    10,    12,    14,    16,     3,    20,     6,     8,
   nil,   nil,    15,    17,    18,    19,    21,     1,     4,   nil,
     3,   nil,     6,     8,   nil,   nil,    15,    17,    18,    19,
    21,     1,     4,    13,    34,    35,    39,   nil,   nil,     2,
     5,   nil,     7,    10,    12,    14,    16,    13,    20,   nil,
   nil,   nil,   nil,     2,     5,   nil,     7,    10,    12,    14,
    16,     3,    20,     6,     8,   nil,   nil,    15,    17,    18,
    19,    21,     1,     4,   nil,     3,   nil,     6,     8,   nil,
   nil,    15,    17,    18,    19,    21,     1,     4,    13,   nil,
   nil,   nil,   nil,   nil,     2,     5,   nil,     7,    10,    12,
    14,    16,    13,    20,   nil,   nil,   nil,   nil,     2,     5,
   nil,     7,    10,    12,    14,    16,     3,    20,     6,     8,
   nil,   nil,    15,    17,    18,    19,    21,     1,     4,   nil,
     3,   nil,     6,     8,   nil,   nil,    15,    17,    18,    19,
    21,     1,     4,    13,   nil,   nil,   nil,   nil,   nil,     2,
     5,   nil,     7,    10,    12,    14,    16,    13,    20,   nil,
   nil,   nil,   nil,     2,     5,   nil,     7,    10,    12,    14,
    16,     3,    20,     6,     8,   nil,   nil,    15,    17,    18,
    19,    21,     1,     4,   nil,     3,   nil,     6,     8,   nil,
   nil,    15,    17,    18,    19,    21,     1,     4,    13,   nil,
   nil,   nil,   nil,   nil,     2,     5,   nil,     7,    10,    12,
    14,    16,    13,    20,   nil,   nil,   nil,   nil,     2,     5,
   nil,     7,    10,    12,    14,    16,     3,    20,     6,     8,
   nil,   nil,    15,    17,    18,    19,    21,     1,     4,   nil,
     3,   nil,     6,     8,   nil,   nil,    15,    17,    18,    19,
    21,     1,     4,    13,   nil,   nil,   nil,   nil,   nil,     2,
     5,   nil,     7,    10,    12,    14,    16,    13,    20,   nil,
   nil,   nil,   nil,     2,     5,   nil,     7,    10,    12,    14,
    16,     3,    20,     6,     8,   nil,   nil,    15,    17,    18,
    19,    21,     1,     4,   nil,     3,   nil,     6,     8,   nil,
   nil,    15,    17,    18,    19,    21,     1,     4,    13,   nil,
   nil,   nil,   nil,   nil,     2,     5,   nil,     7,    10,    12,
    14,    16,    13,    20,   nil,   nil,   nil,   nil,     2,     5,
   nil,     7,    10,    12,    14,    16,     3,    20,     6,     8,
   nil,   nil,    15,    17,    18,    19,    21,     1,     4,   nil,
     3,   nil,     6,     8,   nil,   nil,    15,    17,    18,    19,
    21,     1,     4,    13,   nil,   nil,   nil,   nil,   nil,     2,
     5,   nil,     7,    10,    12,    14,    16,    13,    20,   nil,
   nil,   nil,   nil,     2,     5,   nil,     7,    10,    12,    14,
    16,     3,    20,     6,     8,   nil,   nil,    15,    17,    18,
    19,    21,     1,     4,   nil,     3,   nil,     6,     8,   nil,
   nil,    15,    17,    18,    19,    21,     1,     4,    13,   nil,
   nil,   nil,   nil,   nil,     2,     5,   nil,     7,    10,    12,
    14,    16,    13,    20,   nil,   nil,   nil,   nil,     2,     5,
   nil,     7,    10,    12,    14,    16,     3,    20,     6,     8,
   nil,   nil,    15,    17,    18,    19,    21,     1,     4,   nil,
     3,   nil,     6,     8,   nil,   nil,    15,    17,    18,    19,
    21,     1,     4,    13,   nil,   nil,   nil,   nil,   nil,     2,
     5,   nil,     7,    10,    12,    14,    16,    13,    20,   nil,
   nil,   nil,   nil,     2,     5,   nil,     7,    10,    12,    14,
    16,     3,    20,     6,     8,   nil,   nil,    15,    17,    18,
    19,    21,     1,     4,   nil,     3,   nil,     6,     8,   nil,
   nil,    15,    17,    18,    19,    21,     1,     4,    13,   nil,
   nil,   nil,   nil,   nil,     2,     5,   nil,     7,    10,    12,
    14,    16,    13,    20,   nil,   nil,   nil,   nil,     2,     5,
   nil,     7,    10,    12,    14,    16,     3,    20,     6,     8,
   nil,   nil,    15,    17,    18,    19,    21,     1,     4,   nil,
     3,   nil,     6,     8,   nil,   nil,    15,    17,    18,    19,
    21,     1,     4,    13,   nil,   nil,   nil,   nil,   nil,     2,
     5,   nil,     7,    10,    12,    14,    16,    13,    20,   nil,
   nil,   nil,   nil,     2,     5,   nil,     7,    10,    12,    14,
    16,     3,    20,     6,     8,   nil,   nil,    15,    17,    18,
    19,    21,     1,     4,   nil,     3,   nil,     6,     8,   nil,
   nil,    15,    17,    18,    19,    21,     1,     4,    34,    35,
    39,   nil,    43,    45,    47,    50,    52,   nil,   nil,    32,
   nil,   nil,   nil,   nil,   nil,    48,   nil,    53,    30,    31,
    33,    36,    37,    40,    42,    44,    46,    49,    51,   nil,
    61,   nil,   nil,    38,    41,    34,    35,    39,   nil,    43,
    45,    47,    50,    52,   nil,   nil,    32,   nil,   nil,   nil,
   nil,   nil,    48,   nil,    53,    30,    31,    33,    36,    37,
    40,    42,    44,    46,    49,    51,   nil,   nil,   nil,   nil,
    38,    41,    34,    35,    39,   nil,    43,    45,    47,    50,
    52,   nil,   nil,    32,   nil,   nil,   nil,   nil,   nil,    48,
   nil,    53,    30,    31,    33,    36,    37,    40,    42,    44,
    46,    49,    51,   nil,   nil,   nil,   nil,    38,    41,    34,
    35,    39,   nil,    43,    45,    47,    50,    52,   nil,   nil,
    32,   nil,   nil,   nil,   nil,   nil,    48,   nil,    53,    30,
    31,    33,    36,    37,    40,    42,    44,    46,    49,    51,
   nil,    34,    35,    39,    38,    43,    45,    47,    50,    52,
   nil,   nil,    32,   nil,   nil,   nil,   nil,   nil,    48,   nil,
    53,    30,    31,    33,    36,    37,    40,    42,    44,    46,
    49,    51,    34,    35,    39,   nil,    43,    45,    47,    50,
    52,   nil,   nil,    32,   nil,   nil,   nil,   nil,   nil,    48,
   nil,    53,    30,    31,    33,    36,    37,    40,    42,    44,
    46,    49,    51,    34,    35,    39,   nil,    43,    45,    47,
    50,    52,   nil,   nil,    32,   nil,   nil,   nil,   nil,   nil,
    48,   nil,    53,    30,    31,    33,    36,    37,    40,    42,
    44,    46,    49,    51,    34,    35,    39,   nil,    43,    45,
    47,    50,    52,   nil,   nil,    32,   nil,   nil,   nil,   nil,
   nil,    48,   nil,    53,    30,    31,    33,    36,    37,    40,
    42,    44,    46,    34,    35,    39,   nil,    43,    45,    47,
    50,    52,   nil,   nil,    32,   nil,   nil,   nil,   nil,   nil,
    48,   nil,    53,    30,    31,    33,    36,    37,    40,    42,
    44,    46,    34,    35,    39,   nil,    43,    45,    47,    50,
    52,   nil,   nil,    32,   nil,   nil,   nil,   nil,   nil,    48,
   nil,    53,    30,    31,    33,    36,    37,    40,    34,    35,
    39,   nil,    43,    45,    47,    50,    52,   nil,   nil,    32,
   nil,   nil,   nil,   nil,   nil,    48,   nil,    53,    30,    31,
    33,    36,    37,    40,    34,    35,    39,   nil,    43,    45,
    47,    50,    52,   nil,   nil,    32,   nil,   nil,   nil,   nil,
   nil,    48,   nil,    53,    30,    31,    33,    36,    37,    40,
    34,    35,    39,   nil,    43,    45,    47,    50,    52,   nil,
   nil,    32,   nil,   nil,   nil,   nil,   nil,    48,   nil,    53,
    30,    31,    33,    36,    34,    35,    39,   nil,    43,    45,
    47,    50,    52,   nil,   nil,    32,   nil,   nil,   nil,   nil,
   nil,    48,   nil,    53,    30,    31,    33,    36,    34,    35,
    39,   nil,    43,    45,    47,    50,    52,   nil,   nil,    32,
   nil,   nil,    34,    35,    39,    48,    43,    45,    47,    50,
    52,   nil,   nil,    32,   nil,   nil,    34,    35,    39,    48,
    43,    45,    47,    50,    52,   nil,   nil,    32,   nil,   nil,
    34,    35,    39,    48,    43,    45,    47,    50,    52,   nil,
   nil,    32,   nil,   nil,    34,    35,    39,    48,    43,    45,
    47,    50,    52,   nil,   nil,    32,   nil,   nil,   nil,   nil,
   nil,    48 ]

racc_action_check = [
    55,    55,    55,    55,    55,    55,    55,    55,    55,    55,
    55,    55,    55,    55,    55,    55,    55,    55,    55,    55,
    55,    55,    55,    55,    55,    55,    55,    55,    55,    55,
    55,    55,     9,    55,    55,    55,    55,    55,    55,    55,
    55,    55,    55,    55,    22,    22,    22,    22,    22,    22,
    22,    22,    22,    22,    22,    22,    22,    22,    22,    22,
    22,    22,    22,    22,    22,    22,    22,    22,    22,    22,
    22,    22,    22,    22,    22,    22,    68,    22,    22,    22,
    22,    22,    22,    22,    22,    22,    22,    22,     0,    87,
    87,    87,    28,    32,     0,     0,    39,     0,     0,     0,
     0,     0,     5,     0,    60,    60,    60,   nil,     5,     5,
   nil,     5,     5,     5,     5,     5,     0,     5,     0,     0,
   nil,   nil,     0,     0,     0,     0,     0,     0,     0,   nil,
     5,   nil,     5,     5,   nil,   nil,     5,     5,     5,     5,
     5,     5,     5,     6,    59,    59,    59,   nil,   nil,     6,
     6,   nil,     6,     6,     6,     6,     6,     7,     6,    26,
    26,    26,   nil,     7,     7,   nil,     7,     7,     7,     7,
     7,     6,     7,     6,     6,   nil,   nil,     6,     6,     6,
     6,     6,     6,     6,   nil,     7,   nil,     7,     7,   nil,
   nil,     7,     7,     7,     7,     7,     7,     7,     8,    57,
    57,    57,   nil,   nil,     8,     8,   nil,     8,     8,     8,
     8,     8,    49,     8,    56,    56,    56,   nil,    49,    49,
   nil,    49,    49,    49,    49,    49,     8,    49,     8,     8,
   nil,   nil,     8,     8,     8,     8,     8,     8,     8,   nil,
    49,   nil,    49,    49,   nil,   nil,    49,    49,    49,    49,
    49,    49,    49,    10,    83,    83,    83,   nil,   nil,    10,
    10,   nil,    10,    10,    10,    10,    10,    48,    10,    85,
    85,    85,   nil,    48,    48,   nil,    48,    48,    48,    48,
    48,    10,    48,    10,    10,   nil,   nil,    10,    10,    10,
    10,    10,    10,    10,   nil,    48,   nil,    48,    48,   nil,
   nil,    48,    48,    48,    48,    48,    48,    48,    12,    76,
    76,    76,   nil,   nil,    12,    12,   nil,    12,    12,    12,
    12,    12,    13,    12,    54,    54,    54,   nil,    13,    13,
   nil,    13,    13,    13,    13,    13,    12,    13,    12,    12,
   nil,   nil,    12,    12,    12,    12,    12,    12,    12,   nil,
    13,   nil,    13,    13,   nil,   nil,    13,    13,    13,    13,
    13,    13,    13,    14,    78,    78,    78,   nil,   nil,    14,
    14,   nil,    14,    14,    14,    14,    14,    16,    14,    29,
    29,    29,   nil,    16,    16,   nil,    16,    16,    16,    16,
    16,    14,    16,    14,    14,   nil,   nil,    14,    14,    14,
    14,    14,    14,    14,   nil,    16,   nil,    16,    16,   nil,
   nil,    16,    16,    16,    16,    16,    16,    16,    18,    80,
    80,    80,   nil,   nil,    18,    18,   nil,    18,    18,    18,
    18,    18,    20,    18,    81,    81,    81,   nil,    20,    20,
   nil,    20,    20,    20,    20,    20,    18,    20,    18,    18,
   nil,   nil,    18,    18,    18,    18,    18,    18,    18,   nil,
    20,   nil,    20,    20,   nil,   nil,    20,    20,    20,    20,
    20,    20,    20,     2,    24,    24,    24,   nil,   nil,     2,
     2,   nil,     2,     2,     2,     2,     2,    47,     2,   nil,
   nil,   nil,   nil,    47,    47,   nil,    47,    47,    47,    47,
    47,     2,    47,     2,     2,   nil,   nil,     2,     2,     2,
     2,     2,     2,     2,   nil,    47,   nil,    47,    47,   nil,
   nil,    47,    47,    47,    47,    47,    47,    47,    46,   nil,
   nil,   nil,   nil,   nil,    46,    46,   nil,    46,    46,    46,
    46,    46,    50,    46,   nil,   nil,   nil,   nil,    50,    50,
   nil,    50,    50,    50,    50,    50,    46,    50,    46,    46,
   nil,   nil,    46,    46,    46,    46,    46,    46,    46,   nil,
    50,   nil,    50,    50,   nil,   nil,    50,    50,    50,    50,
    50,    50,    50,    45,   nil,   nil,   nil,   nil,   nil,    45,
    45,   nil,    45,    45,    45,    45,    45,    44,    45,   nil,
   nil,   nil,   nil,    44,    44,   nil,    44,    44,    44,    44,
    44,    45,    44,    45,    45,   nil,   nil,    45,    45,    45,
    45,    45,    45,    45,   nil,    44,   nil,    44,    44,   nil,
   nil,    44,    44,    44,    44,    44,    44,    44,     3,   nil,
   nil,   nil,   nil,   nil,     3,     3,   nil,     3,     3,     3,
     3,     3,    43,     3,   nil,   nil,   nil,   nil,    43,    43,
   nil,    43,    43,    43,    43,    43,     3,    43,     3,     3,
   nil,   nil,     3,     3,     3,     3,     3,     3,     3,   nil,
    43,   nil,    43,    43,   nil,   nil,    43,    43,    43,    43,
    43,    43,    43,    30,   nil,   nil,   nil,   nil,   nil,    30,
    30,   nil,    30,    30,    30,    30,    30,    31,    30,   nil,
   nil,   nil,   nil,    31,    31,   nil,    31,    31,    31,    31,
    31,    30,    31,    30,    30,   nil,   nil,    30,    30,    30,
    30,    30,    30,    30,   nil,    31,   nil,    31,    31,   nil,
   nil,    31,    31,    31,    31,    31,    31,    31,    52,   nil,
   nil,   nil,   nil,   nil,    52,    52,   nil,    52,    52,    52,
    52,    52,    33,    52,   nil,   nil,   nil,   nil,    33,    33,
   nil,    33,    33,    33,    33,    33,    52,    33,    52,    52,
   nil,   nil,    52,    52,    52,    52,    52,    52,    52,   nil,
    33,   nil,    33,    33,   nil,   nil,    33,    33,    33,    33,
    33,    33,    33,    34,   nil,   nil,   nil,   nil,   nil,    34,
    34,   nil,    34,    34,    34,    34,    34,    35,    34,   nil,
   nil,   nil,   nil,    35,    35,   nil,    35,    35,    35,    35,
    35,    34,    35,    34,    34,   nil,   nil,    34,    34,    34,
    34,    34,    34,    34,   nil,    35,   nil,    35,    35,   nil,
   nil,    35,    35,    35,    35,    35,    35,    35,    36,   nil,
   nil,   nil,   nil,   nil,    36,    36,   nil,    36,    36,    36,
    36,    36,    37,    36,   nil,   nil,   nil,   nil,    37,    37,
   nil,    37,    37,    37,    37,    37,    36,    37,    36,    36,
   nil,   nil,    36,    36,    36,    36,    36,    36,    36,   nil,
    37,   nil,    37,    37,   nil,   nil,    37,    37,    37,    37,
    37,    37,    37,    38,   nil,   nil,   nil,   nil,   nil,    38,
    38,   nil,    38,    38,    38,    38,    38,    51,    38,   nil,
   nil,   nil,   nil,    51,    51,   nil,    51,    51,    51,    51,
    51,    38,    51,    38,    38,   nil,   nil,    38,    38,    38,
    38,    38,    38,    38,   nil,    51,   nil,    51,    51,   nil,
   nil,    51,    51,    51,    51,    51,    51,    51,    40,   nil,
   nil,   nil,   nil,   nil,    40,    40,   nil,    40,    40,    40,
    40,    40,    41,    40,   nil,   nil,   nil,   nil,    41,    41,
   nil,    41,    41,    41,    41,    41,    40,    41,    40,    40,
   nil,   nil,    40,    40,    40,    40,    40,    40,    40,   nil,
    41,   nil,    41,    41,   nil,   nil,    41,    41,    41,    41,
    41,    41,    41,    42,   nil,   nil,   nil,   nil,   nil,    42,
    42,   nil,    42,    42,    42,    42,    42,    53,    42,   nil,
   nil,   nil,   nil,    53,    53,   nil,    53,    53,    53,    53,
    53,    42,    53,    42,    42,   nil,   nil,    42,    42,    42,
    42,    42,    42,    42,   nil,    53,   nil,    53,    53,   nil,
   nil,    53,    53,    53,    53,    53,    53,    53,    23,    23,
    23,   nil,    23,    23,    23,    23,    23,   nil,   nil,    23,
   nil,   nil,   nil,   nil,   nil,    23,   nil,    23,    23,    23,
    23,    23,    23,    23,    23,    23,    23,    23,    23,   nil,
    23,   nil,   nil,    23,    23,    58,    58,    58,   nil,    58,
    58,    58,    58,    58,   nil,   nil,    58,   nil,   nil,   nil,
   nil,   nil,    58,   nil,    58,    58,    58,    58,    58,    58,
    58,    58,    58,    58,    58,    58,   nil,   nil,   nil,   nil,
    58,    58,    11,    11,    11,   nil,    11,    11,    11,    11,
    11,   nil,   nil,    11,   nil,   nil,   nil,   nil,   nil,    11,
   nil,    11,    11,    11,    11,    11,    11,    11,    11,    11,
    11,    11,    11,   nil,   nil,   nil,   nil,    11,    11,    74,
    74,    74,   nil,    74,    74,    74,    74,    74,   nil,   nil,
    74,   nil,   nil,   nil,   nil,   nil,    74,   nil,    74,    74,
    74,    74,    74,    74,    74,    74,    74,    74,    74,    74,
   nil,    71,    71,    71,    74,    71,    71,    71,    71,    71,
   nil,   nil,    71,   nil,   nil,   nil,   nil,   nil,    71,   nil,
    71,    71,    71,    71,    71,    71,    71,    71,    71,    71,
    71,    71,    27,    27,    27,   nil,    27,    27,    27,    27,
    27,   nil,   nil,    27,   nil,   nil,   nil,   nil,   nil,    27,
   nil,    27,    27,    27,    27,    27,    27,    27,    27,    27,
    27,    27,    27,    25,    25,    25,   nil,    25,    25,    25,
    25,    25,   nil,   nil,    25,   nil,   nil,   nil,   nil,   nil,
    25,   nil,    25,    25,    25,    25,    25,    25,    25,    25,
    25,    25,    25,    25,    84,    84,    84,   nil,    84,    84,
    84,    84,    84,   nil,   nil,    84,   nil,   nil,   nil,   nil,
   nil,    84,   nil,    84,    84,    84,    84,    84,    84,    84,
    84,    84,    84,    82,    82,    82,   nil,    82,    82,    82,
    82,    82,   nil,   nil,    82,   nil,   nil,   nil,   nil,   nil,
    82,   nil,    82,    82,    82,    82,    82,    82,    82,    82,
    82,    82,    79,    79,    79,   nil,    79,    79,    79,    79,
    79,   nil,   nil,    79,   nil,   nil,   nil,   nil,   nil,    79,
   nil,    79,    79,    79,    79,    79,    79,    79,    77,    77,
    77,   nil,    77,    77,    77,    77,    77,   nil,   nil,    77,
   nil,   nil,   nil,   nil,   nil,    77,   nil,    77,    77,    77,
    77,    77,    77,    77,    75,    75,    75,   nil,    75,    75,
    75,    75,    75,   nil,   nil,    75,   nil,   nil,   nil,   nil,
   nil,    75,   nil,    75,    75,    75,    75,    75,    75,    75,
    73,    73,    73,   nil,    73,    73,    73,    73,    73,   nil,
   nil,    73,   nil,   nil,   nil,   nil,   nil,    73,   nil,    73,
    73,    73,    73,    73,    70,    70,    70,   nil,    70,    70,
    70,    70,    70,   nil,   nil,    70,   nil,   nil,   nil,   nil,
   nil,    70,   nil,    70,    70,    70,    70,    70,    86,    86,
    86,   nil,    86,    86,    86,    86,    86,   nil,   nil,    86,
   nil,   nil,    69,    69,    69,    86,    69,    69,    69,    69,
    69,   nil,   nil,    69,   nil,   nil,    66,    66,    66,    69,
    66,    66,    66,    66,    66,   nil,   nil,    66,   nil,   nil,
    63,    63,    63,    66,    63,    63,    63,    63,    63,   nil,
   nil,    63,   nil,   nil,    64,    64,    64,    63,    64,    64,
    64,    64,    64,   nil,   nil,    64,   nil,   nil,   nil,   nil,
   nil,    64 ]

racc_action_pointer = [
    83,   nil,   468,   633,   nil,    97,   138,   152,   193,    32,
   248,  1150,   303,   317,   358,   nil,   372,   nil,   413,   nil,
   427,   nil,    42,  1076,   472,  1281,   157,  1250,    92,   377,
   688,   702,    53,   757,   798,   812,   853,   867,   908,    56,
   963,   977,  1018,   647,   592,   578,   523,   482,   262,   207,
   537,   922,   743,  1032,   322,    -2,   212,   197,  1113,   142,
   102,   nil,   nil,  1538,  1552,   nil,  1524,   nil,    74,  1510,
  1472,  1219,   nil,  1448,  1187,  1422,   307,  1396,   362,  1370,
   417,   432,  1341,   252,  1312,   267,  1496,    87 ]

racc_action_default = [
   -45,   -31,   -45,   -45,   -32,   -45,   -45,   -45,   -45,   -45,
   -45,    -1,   -45,   -45,   -45,    -3,   -45,   -33,   -45,   -29,
   -45,   -30,   -45,   -45,   -24,   -37,   -25,   -23,   -45,   -26,
   -45,   -45,   -45,   -45,   -45,   -45,   -45,   -45,   -45,   -45,
   -45,   -45,   -45,   -45,   -45,   -45,   -45,   -45,   -45,   -45,
   -45,   -45,   -45,   -45,   -34,   -45,   -36,   -35,   -27,    -8,
    -7,    -4,    88,   -12,   -13,   -28,   -16,    -2,   -22,   -17,
   -43,   -10,    -6,   -44,   -15,   -40,   -14,   -42,   -18,   -41,
   -20,    -9,   -38,   -19,   -39,   -21,   -11,    -5 ]

racc_goto_table = [
    11,     9,    22,    23,   nil,    24,    25,    26,    27,   nil,
    29,   nil,    54,    55,    56,   nil,    57,   nil,    58,   nil,
    59,   nil,    60,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    63,    64,   nil,    66,    67,    68,    69,    70,    71,   nil,
    73,    74,    75,    76,    77,    78,    79,    80,    81,    82,
    83,    84,    85,    86,   nil,    87 ]

racc_goto_check = [
     2,     1,     2,     2,   nil,     2,     2,     2,     2,   nil,
     2,   nil,     2,     2,     2,   nil,     2,   nil,     2,   nil,
     2,   nil,     2,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
     2,     2,   nil,     2,     2,     2,     2,     2,     2,   nil,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,   nil,     2 ]

racc_goto_pointer = [
   nil,     1,     0 ]

racc_goto_default = [
   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 47, :_reduce_none,
  3, 48, :_reduce_2,
  1, 48, :_reduce_3,
  3, 48, :_reduce_4,
  3, 48, :_reduce_5,
  3, 48, :_reduce_6,
  3, 48, :_reduce_7,
  2, 48, :_reduce_8,
  3, 48, :_reduce_9,
  3, 48, :_reduce_10,
  3, 48, :_reduce_11,
  3, 48, :_reduce_12,
  3, 48, :_reduce_13,
  3, 48, :_reduce_14,
  3, 48, :_reduce_15,
  3, 48, :_reduce_16,
  3, 48, :_reduce_17,
  3, 48, :_reduce_18,
  3, 48, :_reduce_19,
  3, 48, :_reduce_20,
  3, 48, :_reduce_21,
  3, 48, :_reduce_22,
  2, 48, :_reduce_23,
  2, 48, :_reduce_24,
  2, 48, :_reduce_25,
  2, 48, :_reduce_26,
  2, 48, :_reduce_27,
  3, 48, :_reduce_28,
  1, 48, :_reduce_29,
  1, 48, :_reduce_30,
  1, 48, :_reduce_31,
  1, 48, :_reduce_32,
  1, 48, :_reduce_33,
  2, 48, :_reduce_34,
  2, 48, :_reduce_35,
  2, 48, :_reduce_36,
  2, 48, :_reduce_37,
  3, 48, :_reduce_38,
  3, 48, :_reduce_39,
  3, 48, :_reduce_40,
  3, 48, :_reduce_41,
  3, 48, :_reduce_42,
  3, 48, :_reduce_43,
  3, 48, :_reduce_44 ]

racc_reduce_n = 45

racc_shift_n = 88

racc_token_table = {
  false => 0,
  :error => 1,
  :COMMA => 2,
  :WHERE => 3,
  :AS => 4,
  :ANY => 5,
  :JOIN => 6,
  :UNION => 7,
  :IN => 8,
  :SET_MINUS => 9,
  :INTERSECT => 10,
  :ALL => 11,
  :EXISTS => 12,
  :GROUPAS => 13,
  :MAX => 14,
  :MIN => 15,
  :NOT => 16,
  :PICKRANDOM => 17,
  :SUM => 18,
  :DIFFERENCE => 19,
  :AVG => 20,
  :EQUAL => 21,
  :GREATEREQUAL => 22,
  :GREATER => 23,
  :SMALLEREQUAL => 24,
  :SMALLER => 25,
  :AND => 26,
  :OR => 27,
  :MULTIPLY => 28,
  :DIVIDE => 29,
  :MODULO => 30,
  :PLUS => 31,
  :MINUS => 32,
  :LEFT_ROUND_BRACKET => 33,
  :RIGHT_ROUND_BRACKET => 34,
  :STRUCT => 35,
  :BAG => 36,
  :DOT => 37,
  :ORDERBY => 38,
  :expr_without_coma => 39,
  :NAME => 40,
  :UNIQUE => 41,
  :INTEGER_LITERAL => 42,
  :DOUBLE_LITERAL => 43,
  :STRING_LITERAL => 44,
  :BOOLEAN_LITERAL => 45 }

racc_nt_base = 46

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "COMMA",
  "WHERE",
  "AS",
  "ANY",
  "JOIN",
  "UNION",
  "IN",
  "SET_MINUS",
  "INTERSECT",
  "ALL",
  "EXISTS",
  "GROUPAS",
  "MAX",
  "MIN",
  "NOT",
  "PICKRANDOM",
  "SUM",
  "DIFFERENCE",
  "AVG",
  "EQUAL",
  "GREATEREQUAL",
  "GREATER",
  "SMALLEREQUAL",
  "SMALLER",
  "AND",
  "OR",
  "MULTIPLY",
  "DIVIDE",
  "MODULO",
  "PLUS",
  "MINUS",
  "LEFT_ROUND_BRACKET",
  "RIGHT_ROUND_BRACKET",
  "STRUCT",
  "BAG",
  "DOT",
  "ORDERBY",
  "expr_without_coma",
  "NAME",
  "UNIQUE",
  "INTEGER_LITERAL",
  "DOUBLE_LITERAL",
  "STRING_LITERAL",
  "BOOLEAN_LITERAL",
  "$start",
  "target",
  "expr" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

# reduce 1 omitted

module_eval(<<'.,.,', 'SBQL.racc', 19)
  def _reduce_2(val, _values, result)
     result = CommaExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 20)
  def _reduce_3(val, _values, result)
     result = e 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 21)
  def _reduce_4(val, _values, result)
     result = StructExpression.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 22)
  def _reduce_5(val, _values, result)
     result = AnyExpression.new(val[1],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 23)
  def _reduce_6(val, _values, result)
     result = AsExpression.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 24)
  def _reduce_7(val, _values, result)
     result = AllExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 25)
  def _reduce_8(val, _values, result)
    result = AvgExpression.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 26)
  def _reduce_9(val, _values, result)
     result = DifferentExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 27)
  def _reduce_10(val, _values, result)
     result = DotExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 28)
  def _reduce_11(val, _values, result)
     result = EqualExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 29)
  def _reduce_12(val, _values, result)
     result = GreatherEqualExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 30)
  def _reduce_13(val, _values, result)
     result = GreatherExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 31)
  def _reduce_14(val, _values, result)
     result = JoinExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 32)
  def _reduce_15(val, _values, result)
     result = OrderByExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 33)
  def _reduce_16(val, _values, result)
     result = LessEqualExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 34)
  def _reduce_17(val, _values, result)
     result = LessExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 35)
  def _reduce_18(val, _values, result)
     result = UnionExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 36)
  def _reduce_19(val, _values, result)
     result = SetMinusExpression.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 37)
  def _reduce_20(val, _values, result)
     result = InExpression.new(val[0], val[2])
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 38)
  def _reduce_21(val, _values, result)
     result = IntersectExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 39)
  def _reduce_22(val, _values, result)
     result = WhereExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 40)
  def _reduce_23(val, _values, result)
     result = BagExpression.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 41)
  def _reduce_24(val, _values, result)
     result = ExistsExpression.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 42)
  def _reduce_25(val, _values, result)
     result = MaxExpression.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 43)
  def _reduce_26(val, _values, result)
     result = MinExpression.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 44)
  def _reduce_27(val, _values, result)
     result = new UniqueExpression(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 45)
  def _reduce_28(val, _values, result)
     result = GroupAsExpression.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 46)
  def _reduce_29(val, _values, result)
     result = (val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 47)
  def _reduce_30(val, _values, result)
     result = (val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 48)
  def _reduce_31(val, _values, result)
     result = (val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 49)
  def _reduce_32(val, _values, result)
     result = (val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 50)
  def _reduce_33(val, _values, result)
     result = NameExpression.new(val[0])
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 51)
  def _reduce_34(val, _values, result)
     result = NotExpression.new(val[1])  
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 52)
  def _reduce_35(val, _values, result)
     result = SumExpression.new(val[1])  
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 53)
  def _reduce_36(val, _values, result)
     result = PickRandomExpression.new(val[1])  
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 54)
  def _reduce_37(val, _values, result)
     result = StructExpression.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 55)
  def _reduce_38(val, _values, result)
     result = PlusExpression.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 56)
  def _reduce_39(val, _values, result)
     result = MinusExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 57)
  def _reduce_40(val, _values, result)
     result = MultiplyExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 58)
  def _reduce_41(val, _values, result)
     result = ModuloExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 59)
  def _reduce_42(val, _values, result)
     result = DivideExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 60)
  def _reduce_43(val, _values, result)
     result = AndExpression.new(val[0],val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'SBQL.racc', 61)
  def _reduce_44(val, _values, result)
     result = OrExpression.new(val[0],val[2]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class SBQLParser
